controller_list:
  - name: "position_trajectory_controller"
    action_ns: follow_joint_trajectory
    default: true
    type: FollowJointTrajectory
    joints: [joint_a1, joint_a2, joint_a3, joint_a4, joint_a5, joint_a6]
