# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_a1:
    has_velocity_limits: true
    max_velocity: 2.72271363311
    has_acceleration_limits: false
    max_acceleration: 0
  joint_a2:
    has_velocity_limits: true
    max_velocity: 2.72271363311
    has_acceleration_limits: false
    max_acceleration: 0
  joint_a3:
    has_velocity_limits: true
    max_velocity: 2.72271363311
    has_acceleration_limits: false
    max_acceleration: 0
  joint_a4:
    has_velocity_limits: true
    max_velocity: 5.75958653158
    has_acceleration_limits: false
    max_acceleration: 0
  joint_a5:
    has_velocity_limits: true
    max_velocity: 5.75958653158
    has_acceleration_limits: false
    max_acceleration: 0
  joint_a6:
    has_velocity_limits: true
    max_velocity: 10.7337748998
    has_acceleration_limits: false
    max_acceleration: 0